### ISSUE TITLE
Items skipped are listed as transcribed - Herbarium

### ISSUE THREAD

**Issue by joanball** [zooniverse/notesFromNature#324]
This seems like a problem some people had a while ago, but still might be an issue? I couldn't replicate it, but it may be a glitch for people who have been working on records for awhile?  Or maybe it is fixed...
  
http://talk.notesfromnature.org/#/boards/BNN0000002/discussions/DNN00001em?page=1&comment_id=530a34ae47bc7273b9005de7

**Comment by chrissnyder** [comment]
Looked today, skipped is in the data export. Closing.
