### ISSUE TITLE
In Firefox 29.0, Enter key is ignored for pull-down menus

### ISSUE THREAD

**Issue by joanball** [zooniverse/notesFromNature#337]
USer posted this issue: http://talk.notesfromnature.org/#/boards/BNN0000002/discussions/DNN00002b4?page=1&comment_id=536d2d52241fe13d480007ae

In pull-down menus it's possible to press Enter instead of clicking on the OK button. However, this has stopped working in Firefox 29.0.

I've submitted a more detailed bug report to Mozilla at https://bugzilla.mozilla.org/show_bug.cgi?id=1008244.

A developer is asking for a smaller test case, but I'm out of my depth here. Would it be possible for an NfN/Zooniverse developer to engage with Mozilla?

**Comment by chrissnyder** [comment]
Incredibly enough, looks like Firefox fixed this bug. Works in later versions.
