### ISSUE TITLE
ipad compatibility 

### ISSUE THREAD

**Issue by joanball** [zooniverse/notesFromNature#342]
There are some recent comments about this...

I am trying to do Ornithology. I have an ipad 2. The green line ,what I am meant to be working on jumps around out of my control.I had similar problems with the cursor in War Diaries so have given up. Any help?
http://talk.notesfromnature.org/#/boards/BNN0000002/discussions/DNN00002n3?page=1&comment_id=53d73fe10d43f703a6000de3

**Comment by chrissnyder** [comment]
Unlikely we'll achieve tablet compatibility anytime soon.
