### ISSUE TITLE
Stuttering still happening w/ transcriptions

### ISSUE THREAD

**Issue by robgur** [zooniverse/notesFromNature#347]
From our most invested transcriber (he has done thousands as far as I can tell)....

"This is still occurring... just had it happen and in the Herbarium. It seems to be caused by cache or other leftover data, as if I reopen the Herbarium transcription page without first going to and refreshing the main page (the one with the man in the red and white shirt) then after doing a transcription when the next one loads it will stutter and then skip to the next specimen and the "Got it - let me transcribe" overlay dialog will appear as if I just started again.

Usually when this happens I stop and close/relaunch the browser/reload the start page and it doesn't reoccur, but this time I didn't. Instead I did another transcription. When I completed the same stutter and reload of the overlay happened, but my transcription count went up by 4. I did it a few more times and it went up by 4, 7 and 15 respectively (doubled minus one... that may be significant.) At this point it hung so I shut the browser and it's fine now."

**Comment by chrissnyder** [comment]
Whatever this was, it wouldn't apply to the new interface pan/zoom/drag interface, so closing this for now. Re-open if the behavior still exists and can be replicated
