### ISSUE TITLE
Can't enter same data for county and city

### ISSUE THREAD

**Issue by DarrenMcRoy** [zooniverse/notesFromNature#354]
A user reports that he tried to enter "San Francisco" for both city and county (since San Fran is both the city and the county), but got rejected.

Can we fix this? Sometimes the city name is indeed the same as the county.

http://talk.notesfromnature.org/#/boards/BNN0000002/discussions/DNN00003o3?page=1&comment_id=54e3b2286975267adc0000f0

**Comment by denslowm** [comment]
@DarrenMcRoy  -- Assuming I understand correctly, San Fransisco would go into the County drop down and then into the (free text) Locality field. There is no City field. 

I don't see what the bug is. Am I missing something?

**Comment by DarrenMcRoy** [comment]
Hm. I'm going to check and try to get more detail from the user.

**Comment by chrissnyder** [comment]
Closing pending clarification.
