### ISSUE TITLE
Ornithological - add option to duplicate rows

### ISSUE THREAD

**Issue by DarrenMcRoy** [zooniverse/notesFromNature#362]
A user has requested that we add an option to Ornithological to duplicate rows. Quote:

"Would it be possible to put in a fix so that we can duplicate rows? The year is always the same, the first batch number is mostly the same, often the bird is the same and often the location is the same. If we could copy/duplicate any row this would allow us to copy much of the data and significantly reduce the amount of time required. It would also help to improve our accuracy since much of the data would be copied and reduce our inputting errors."

Something to do once we have the resources?

**Comment by robgur** [comment]
Yes it is called the ditto function and it works in other parts of NFN
but not in Ornithology.  Its been on the list of priority upgrades (for a
long time).
