### ISSUE TITLE
Examples can't be seen

### ISSUE THREAD

**Issue by denslowm** [zooniverse/notesFromNature#365]
See attached image. Examples are obstructed from view.
Using Firefox.

![Uploading NumberExample.png…]()

**Comment by denslowm** [comment]
![numberexample](https://cloud.githubusercontent.com/assets/2152565/8035547/b5856896-0dae-11e5-9cf9-0d9f7893aa1b.jpeg)

**Comment by denslowm** [comment]
@rafelafrance Is this something you an look into? I just got another report from a user about this. I can confirm that this has been happening for while.

**Comment by rafelafrance** [comment]
I know what the issue is here. In jargon it's z-index problem. Would you be
OK with me moving the examples up a bit? This would be a temporary fix
until I solve the real issue. I would move the examples to be above the
input box that is covering the examples.

**Comment by denslowm** [comment]
Thanks Rafe! I have no problem with that as long as the example can be seen.
