### ISSUE TITLE
Data export script needs update

### ISSUE THREAD

**Issue by trouille** [zooniverse/notesFromNature#383]
Researchers with collections that have been more recently added to the Notes from Nature interface aren't getting their data. Need to update script that does this. Crab Shack is one. Am checking with research teams if there are others being left out as well.

**Comment by denslowm** [comment]
@trouille -- I think this the same as #382 . If so I can remove that one.

We are missing the following:
Crabs
Herbarium: University of South Florida
Herbarium: Florida State University
Herbarium: Botanical Research Institute of Texas

We are getting Southeastern Louisiana University (Herbarium). 

I think we can put all the herbarium ones in one a single data dump, but it would be helpful to include some kind of code or name to separate the different museums within the file.

**Comment by parrish** [comment]
This is setup now.  Each collection will be exported separately.

**Comment by denslowm** [comment]
Thanks @parrish!
So you mean that each with come as a separate link?

Right now it looks something like this:
![image](https://cloud.githubusercontent.com/assets/2152565/11351900/7b14881e-91f6-11e5-88c3-bb2d5206ce87.png)

**Comment by parrish** [comment]
Yep.  You'll have separate links for each one.  So five new links: BRIT, FSU, USF, crabs, and Calbug-expeditions.

**Comment by denslowm** [comment]
That will work great. 

I think there will be 8 links though.
Crabs, Ornithology, CalBug expeditions, Macrofungi, 4 herbarium ones...(FSU, USF, BRIT, SELU)
