### ISSUE TITLE
Duplicate images loading in Calbug

### ISSUE THREAD

**Issue by mcbouslog** [zooniverse/notesFromNature#389]
I'll clean-up this issue context asap, just making a few notes for now...

Similar to #388, #387, #385 and #384.  Should consolidate?

Chrome: Version 47.0.2526.111 (64-bit)
Console:
`Uncaught TypeError: Cannot read property 'getBBox' of null`

<img width="1343" alt="screen shot 2016-01-29 at 1 35 10 pm" src="https://cloud.githubusercontent.com/assets/12118751/12686026/43075d22-c68d-11e5-95d9-aa65bd0b4d3c.png">

**Comment by rafelafrance** [comment]
It is probably safe to consolidate #388, #387 & #385. #384 may to be a
different bug related to the area of code.
